### ISSUE TITLE
When offsets used, window should be scrolled so element displays underneath them

### ISSUE THREAD

**Issue by hyfen** [aranja/ember-scroller#1]
Unless I'm misinterpreting the purpose of setting offset elements, we should scroll so that the target element displays below the height of all the offset elements, right? 

If so, I think it's just a matter of changing the `+` to a `-` here: 
https://github.com/aranja/ember-scroller/blob/master/addon/services/scroller.js#L36

**Comment by thorsteinsson** [comment]
Good spot, I hadn't even started using this functionality yet. I've fixed it now.

**Comment by hyfen** [comment]
Thanks!

**Comment by hyfen** [comment]
Think you could bump version?
